AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Debug DATIM Okta integration locally

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 60

Parameters:
  subnetId:
    Type: AWS::SSM::Parameter::Value<String>
    Default: pdap-vpc-PrivateSubnet1Id

  secGroupId:
    Type: AWS::SSM::Parameter::Value<String>
    Default: pdap-vpc-SecurityGroupId

  oktaClientId:
    Type: AWS::SSM::Parameter::Value<String>
    Default: 0oathu4y0sBs9fRFM297

Resources:
  GetByEmail:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: code/getByEmail
      Handler: app.lambda_handler
      Runtime: python3.12
      Architectures:
        - x86_64
      VpcConfig:
        SubnetIds:
          - !Ref subnetId
        SecurityGroupIds:
          - !Ref secGroupId
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: get

