AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Query OKTA API to test it

Globals:
  Function:
    Timeout: 60

Parameters:
  subnetId:
    Type: AWS::SSM::Parameter::Value<String>
    Default: pdap-vpc-PrivateSubnet1Id

  secGroupId:
    Type: AWS::SSM::Parameter::Value<String>
    Default: pdap-vpc-SecurityGroupId

Resources:
  GetByEmail:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: code/getByEmail
      Handler: app.lambda_handler
      Runtime: python3.12
      Architectures:
        - x86_64
      VpcConfig:
        SubnetIds:
          - !Ref subnetId
        SecurityGroupIds:
          - !Ref secGroupId
      Policies:
        - Version: 2012-10-17
          Statement:
            - Sid: GetSecretValue
              Effect: Allow
              Action:
                - secretsmanager:*
              Resource:
                - '*'

Outputs:
  GetByEmail:
    Description: "Function ARN"
    Value: !GetAtt GetByEmail.Arn